### ISSUE TITLE
there was an error reacting to that user 

### ISSUE THREAD

**Issue by thomasm28505** [ajmeese7/multiple-reactions#3] opened 2020-08-19 21:16 UTC
so first off i am on android running termux
i get this error any help? thanks
There was a problem reacting to that user. Are they a bot?
DiscordAPIError: Unknown Message
    at /data/data/com.termux/files/home/selfbots/multiple-reactions/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /data/data/com.termux/files/home/selfbots/multiple-reactions/node_modules/snekfetch/src/index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  path: '/api/v7/channels/745508527518384148/messages/745752378556416019',
  code: 10008,
  method: 'DELETE'
}

**Comment by ajmeese7** [comment] 2020-08-19 21:26
I added in that error message this morning, usually it fails silently. That's one thing that I don't know the cause to. Can you explain the conditions where you got that message, so I can have a better chance at understanding it and preventing it from happening?

**Comment by thomasm28505** [comment] 2020-08-19 21:29
> I added in that error message this morning, usually it fails silently. That's one thing that I don't know the cause to. Can you explain the conditions where you got that message, so I can have a better chance at understanding it and preventing it from happening?

i just set a command called test to just add 1 emoji it wasnt a gif or anything just the smiley emoji. I then just joined a random server to try it and each time i did /test @*whoever the fuck* it gave me that error

**Comment by ajmeese7** [comment] 2020-08-22 14:19
Have you tried it on a normal environment? I'm not sure if it's an issue with the project or with your environment, because I've never tested it on Termux before.

Can you explain your install process and the exact steps you followed, so I can try to track down the cause?

**Comment by thomasm28505** [comment] 2020-08-22 14:32
> Have you tried it on a normal environment? I'm not sure if it's an issue with the project or with your environment, because I've never tested it on Termux before.
> 
> Can you explain your install process and the exact steps you followed, so I can try to track down the cause?

I figured out how to get it to work, for some reason on android you have to put one reaction on a message yourself then you can use the bot to add more.

**Comment by ajmeese7** [comment] 2020-08-22 14:37
Huh, that's strange. I don't know why that behavior exists, but I'm glad you figured it out. Closing this issue for now, but don't hesitate to reach out if there's anything else I can help you with. Cheers!

**Closed as completed by ajmeese7** 2020-08-22 14:37 UTC
